# Generated by Django 4.2.4 on 2023-08-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcreatedmodel',
            name='market_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculator.marketcreatedmodel'),
            preserve_default=False,
        ),
    ]
