# Generated by Django 4.2.4 on 2023-09-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcreatedmodel',
            name='favorite',
            field=models.BooleanField(null=True, unique=True),
        ),
    ]
