# Generated by Django 4.2.4 on 2023-09-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_itemcreatedmodel_market_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcreatedmodel',
            name='market_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculator.marketcreatedmodel'),
        ),
    ]
