# Generated by Django 4.2.4 on 2023-09-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_marketcreatedmodel_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcreatedmodel',
            name='favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
