# Generated by Django 4.2.4 on 2023-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_marketcreatedmodel_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcreatedmodel',
            options={'ordering': ['market_id__user_id']},
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
