# Generated by Django 4.2.4 on 2023-09-17 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_itemcreatedmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcreatedmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
    ]
